env:
  browser: true
  es2021: true

extends:
  - airbnb-base

plugins:
  - fp # Убедитесь, что плагин включен

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: off
  import/extensions: off
  fp/no-mutation:
    - error
    - commonjs: true
      allowThis: true
      exceptions:
        - object: "foo"
          property: "bar"
  fp/no-mutating-methods:
    - error
    - allowedObjects:
        - "_"
        - "R"
        - "fp"
